### PR TITLE
replace icon with Temporary Containers icon

### PR DESCRIPTION
**Pull request by boredsquirrel**
The Temporary Containers addon is [licensed under MIT](https://github.com/stoically/temporary-containers/blob/main/LICENSE), so using the icon is fine.

Also... the maintainer passed away, people struggle to create a fork.

Designwise, the Temporary Container addon is great. It combines the "+" with the stopwatch, fitting perfectly around it.

The current icon is way too detailed, especially the letters are not visible in the used size.

I made my own icons using the Mozilla "multi account containers" fence, but the Temporary containers icon is just better.

fence-icon-dark fence-icon-light

temporary-containers

### CODE REVIEW

**Comment by igorlogius** [comment]
Thanks for makeing this suggestion. 

I generally agree that the current icon is not very good (to detailed), but i am a bit hesitant just re-using an icon that is still well known to represent the "Temporary Container" addon, which is still on AMO. It also feels a bit disrespectful to the creator of TC, which passed away.

I think it would be fine if we created a kind of spin-off icon based on the TC icon, by addin one small visual change to differenciate OiTC from TC.

Let me know if you have a suggestion,

**Comment by boredsquirrel** [comment]
yes I understand that for sure. I will see!

**Comment by igorlogius** [comment]
@boredsquirrel 

One of these maybe?

|TC(MAC)|MAC(TC)|
|---|---|
|mashup_1   |mashup_2   |

**Comment by privacy-advo** [comment]
\+1 for MAC(TC)

**Comment by igorlogius** [comment]
> +1 for MAC(TC)

well, it looks better than the current one.
The clock might be to small to be visible in the toolbar but whatever.
It's progress and i guess if someone has a better design it can always be updated.

**Comment by igorlogius** [comment]
none of the  icons look good, when scaled down and the MAC(TC) one is indistinguishable from the MAC icon. 

So i started experimenting with other alternative designs like 

icon

... but nothing looks good. 

Damn ... how i wish someone with more design skills could help out here ...  i'll need to take a break ... this might take a tad longer than i thought, sorry.

**Comment by boredsquirrel** [comment]
I think my original icon with the fence is good. It works on a small size.

I also think your hourglass icon looks good, may still be a bit detailed, I would maybe just use an hourglass?

**Comment by privacy-advo** [comment]
What about those MIT license icon library? 
Options?
[alarm plus outlined](https://github.com/tabler/tabler-icons/blob/efa07c00285dabe522803946fc0c662005e02460/icons/outline/alarm-plus.svg?plain=1#L4)
[alarm plus filled](https://github.com/tabler/tabler-icons/blob/efa07c00285dabe522803946fc0c662005e02460/icons/filled/alarm.svg?plain=1#L4)

**Comment by boredsquirrel** [comment]
"apps filled" is a good replacement for the current icon

the others are too detailed for the small size.

I would say use that? it is still small but fine.

**Comment by privacy-advo** [comment]
> [alarm plus outlined](https://github.com/tabler/tabler-icons/blob/efa07c00285dabe522803946fc0c662005e02460/icons/outline/alarm-plus.svg?plain=1#L4) 

Alarm plus is close to TC's icon, all corners are rounded. I think it would be perfect. Visually familiar and yet not an identical copy.

**Comment by igorlogius** [comment]
@boredsquirrel 
@privacy-advo 

Thank you both for your suggestions. 
I decided give creating a mash-up icon one more try and the result came out suprisingly well. 

So this will be the new OiTC icon. 

oitc

**Pull request closed without merging**
